// Package locks manages the terminal locks the idle updater reads
// (docs/ARCHITECTURE.md Section 4.1).
//
// Terminal locks and agent locks share a directory but not a lifetime. An
// agent lock is created by the agent-run wrapper and cleaned up after 6 h if
// its process died. A terminal lock is created here when a session opens and
// removed ONLY when the user explicitly closes that session — never on
// disconnect, never on daemon shutdown, never on a timer. Removing one because
// a client went away would let the system update underneath a terminal the
// user still considers open.
package locks

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// DefaultDir matches the path used by agent-run and idle-update-check.sh.
const DefaultDir = "/run/claudecode-locks"

// Prefix marks locks owned by terminal sessions. The updater's stale cleanup
// deliberately matches only "agent-*", so anything created with this prefix is
// exempt from expiry.
const Prefix = "terminal-"

// Manager creates and removes terminal locks in a directory.
type Manager struct {
	dir string
}

// New returns a Manager for dir, creating the directory if needed.
func New(dir string) (*Manager, error) {
	if dir == "" {
		dir = DefaultDir
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return nil, fmt.Errorf("create lock directory %s: %w", dir, err)
	}
	return &Manager{dir: dir}, nil
}

// Dir returns the managed directory.
func (m *Manager) Dir() string { return m.dir }

// Path returns the lock file path for a session id.
func (m *Manager) Path(sessionID string) string {
	return filepath.Join(m.dir, Prefix+sanitize(sessionID))
}

// Acquire creates the lock for a session. It is idempotent: re-acquiring an
// existing lock is not an error, because a daemon restart must not fail just
// because the lock it left behind is still there.
func (m *Manager) Acquire(sessionID string) error {
	f, err := os.OpenFile(m.Path(sessionID), os.O_CREATE|os.O_WRONLY, 0o644)
	if err != nil {
		return fmt.Errorf("acquire terminal lock for %s: %w", sessionID, err)
	}
	return f.Close()
}

// Release removes the lock for a session. Call this ONLY from the explicit
// close path. Removing an absent lock is not an error.
func (m *Manager) Release(sessionID string) error {
	err := os.Remove(m.Path(sessionID))
	if err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("release terminal lock for %s: %w", sessionID, err)
	}
	return nil
}

// Held reports whether a lock exists for a session.
func (m *Manager) Held(sessionID string) bool {
	_, err := os.Stat(m.Path(sessionID))
	return err == nil
}

// List returns the session ids that currently hold a terminal lock.
func (m *Manager) List() ([]string, error) {
	entries, err := os.ReadDir(m.dir)
	if err != nil {
		return nil, fmt.Errorf("list locks in %s: %w", m.dir, err)
	}
	out := []string{}
	for _, e := range entries {
		name := e.Name()
		if strings.HasPrefix(name, Prefix) {
			out = append(out, strings.TrimPrefix(name, Prefix))
		}
	}
	return out, nil
}

// sanitize keeps a session id from escaping the lock directory. Session ids
// are generated by the daemon today, but a lock path built from unvalidated
// input is the kind of thing that becomes a path traversal the moment someone
// adds a "name your session" field.
func sanitize(id string) string {
	var b strings.Builder
	for _, r := range id {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r >= '0' && r <= '9', r == '-', r == '_':
			b.WriteRune(r)
		default:
			b.WriteRune('_')
		}
	}
	return b.String()
}
